### ISSUE TITLE
The popup window should remain open in the old tab even after switching to a new tab

### ISSUE THREAD

**Issue by ErenC61** [jeffnawroth/source-taster#11]
The popup window should remain open in the old tab even after switching to a new tab. This is important when the popup window is used to open a source via a button. Users should not have to restart the process every time they switch tabs.

**Comment by jeffnawroth** [comment]
https://developer.chrome.com/docs/extensions/develop/ui/add-popup

„There is no way to keep the popup open after the user has clicked away.“

**Comment by ErenC61** [comment]
Yeah maybe, just a way to continue without losing the whole progress

**Comment by jeffnawroth** [comment]
Using a side panel instead of a popup solves this problem
